### ISSUE TITLE
Limit markdown to 65535?

### ISSUE THREAD

**Issue by rakkarage** [calibreapp/image-actions#118]
The markdown output can be over 65535 characters if convert many images, which causes error with peter-evans/create-pull-request@v3 since github body can only be 65535. Fixed with truncate action but perhaps there should/could be a limit built in? I guess it is not limited to just being used for github pull requests tho so maybe not. Thanks.

**Comment by lfgcampos** [comment]
Similar to #107 ?

**Comment by lfgcampos** [comment]
`create-pull-request@v6` fixed this: [changelog](https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.0)

> If the pull request body is truncated due to exceeding the maximum length, the action will now suffix the body with the message "...[Pull request body truncated]" to indicate that the body has been truncated.

I haven't tested myself though but maybe just updating the version used by this action will fix it =)

**Comment by JakeSteam** [comment]
@lfgcampos excellent timing, I can confirm v6 fixes it! Just in case anyone else ends up here: 

[Here's a failing run](https://github.com/JakeSteam/blog-personal/actions/runs/7945261894/job/21691710107) on v4, [here's a passing run](https://github.com/JakeSteam/blog-personal/actions/runs/7945295873/job/21691790015) on v6.

Here's the error that was previously shown:
> An error occurred trying to start process '/home/runner/runners/2.313.0/externals/node16/bin/node' with working directory '/home/runner/work/blog-personal/blog-personal'. Argument list too long

And [here's the change](https://github.com/JakeSteam/blog-personal/commit/45c39f811cd1f3e8d98467998eadedef8936daba):
> uses: peter-evans/create-pull-request@v6

**Comment by JakeSteam** [comment]
Limiting the variable length within the `.yml` file is an acceptable workaround. I was only running a one-off job so just used an empty body & echo'd the markdown so that the PR could be successfully created, a proper solution probably includes a `cut` step or something.

My hacky fix let it successfully [create a PR](https://github.com/JakeSteam/blog-personal/pull/14) that changed 1,516 files(!) and saved 186MB(!!!). The details can be seen in the ["Echo markdown" step of the job](https://github.com/JakeSteam/blog-personal/actions/runs/7945443798/job/21692114022).

Here's the full `.yml` for ):

```
# https://github.com/calibreapp/image-actions?tab=readme-ov-file#compress-on-demand-or-on-schedule
name: Compress Images
on:
  workflow_dispatch:
  
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: "${{ secrets.GITHUB_TOKEN }}"
          compressOnly: true
      - name: Echo markdown
        run: echo ${{ steps.calibre.outputs.markdown }}
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v6
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ""
```
