### ISSUE TITLE
[Feature Request] Support for compressing PDFs

### ISSUE THREAD

**Issue by karlhorky** [calibreapp/image-actions#179]
### What problem would this feature solve?

Compress PDFs, which are often a lot larger than they need to be (recently converted a 10MB PDF to ~1MB)

### Describe the solution you’d like to see

Support for PDF files

### Are you willing to work on implementing this solution?

No

### Describe alternatives you’ve considered

- Writing a separate GitHub Actions workflow manually to do this
- Finding a different Action that does this already, eg. some discussion of PDF support over in this Imgbot issue https://github.com/imgbot/Imgbot/issues/332

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by karlhorky** [comment]
## Alternative

A separate GitHub Actions workflow to do this using `ghostscript` (generate an access token for this and add it as a GitHub repo secret called `PDF_COMPRESSION_GITHUB_TOKEN`):

```yaml
name: Compress PDFs
on:
  pull_request:
    # Run only when PDF files are added or changed
    paths:
      - '**.pdf'

jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Compress PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Run apt update
        run: sudo apt update
      - name: Install Ghostscript for compression
        run: sudo apt install -y ghostscript
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Compress PDFs
        run: |
          find . -type f -iname '*.pdf' -not -path "./node_modules/*" | while read file; do
            # Compress the file for screen using Ghostscript
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$file" "$file"
          done
      - name: Commit files
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add **/*.pdf
          git commit -m "Compress PDFs"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PDF_COMPRESSION_GITHUB_TOKEN }}
```
