### ISSUE TITLE
Bug: fails on symlinks

### ISSUE THREAD

**Issue by starzonmyarmz** [calibreapp/image-actions#19]
This action fails on my repo because one of the urls to an image is actually a symlink. Here's the error:

```
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/github/workspace/public/apple-touch-icon.png'
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Maybe a quick fix is to have this action ignore symlinks?

**Comment by benschwarz** [comment]
@starzonmyarmz A way to do this might be to use the `ignorePaths` [configuration option](https://github.com/calibreapp/image-actions#configuration), did you give that a shot?

**Comment by benschwarz** [comment]
Forgot to say: I agree, symlinks should not be followed

**Comment by frenck** [comment]
experiencing the same issue, unfortunately.
Anyway to work around this for now?

**Comment by frenck** [comment]
using this workaround for now:

```yaml
jobs:
  compress:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Find symlinked paths to ignore
        id: find
        run: >-
          echo "::set-output name=ignore::$(find -L src -xtype l -type d | sed -e 's#$#/**#' | head -c -1 | tr '\n' ',')"
      - name: Check ignored paths
        run: echo ${{ steps.find.outputs.ignore }} | tr ',' '\n'
      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          ignorePaths: ${{ steps.find.outputs.ignore }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```
