### ISSUE TITLE
Specify the path trigger

### ISSUE THREAD

**Issue by chenrui333** [calibreapp/image-actions#21]
It would be good to specify the file path for triggering the action.

Right now, it is like this:
```
name: Compress images
on: pull_request
```

Propose:

```
name: Compress images
on:
  pull_request:
    paths:
    - '**.jpeg'
    - '**.png'
    - '**.jpg'
    - '**.webp'
```
