### ISSUE TITLE
No effect with quality 100?

### ISSUE THREAD

**Issue by hugovk** [calibreapp/image-actions#25]
# PR 1: quality 80

PR https://github.com/hugovk/python-logos/pull/1 adds the default workflow in `.github/workflows/calibreapp-image-actions.yml` from:

https://github.com/calibreapp/image-actions#how-to-add-this-to-your-repository

```yml
name: Compress images
on: pull_request
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

# PR 2: quality 100

PR https://github.com/hugovk/python-logos/pull/2 is the same, but with this config in `.github/calibre/image-actions.yml`:

```yml
jpeg:
  quality: 100
png:
  quality: 100
webp:
  quality: 100
```

And the action read in the config:

```
->> Using config: {"jpeg":{"quality":100},"png":{"quality":100},"webp":{"quality":100},"ignorePaths":["node_modules/**"]}
```

https://github.com/hugovk/python-logos/runs/295767221#step:4:7

However, the images in both PRs are binary identical:

![image](https://user-images.githubusercontent.com/1324225/68532387-47b5ee00-0325-11ea-9fca-bcfaa9ca1297.png)

This is surprising, should the images with 100 quality be lossless? I'd expect at least some difference.

Thanks!
