### ISSUE TITLE
[Bug] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by BriceChivu** [calibreapp/image-actions#284]
DISCLAIMER: I have little knowledge of Github actions and workflows. Apologies if my issue is trivial.

**Bug**:
The compression workflow of my images using calibreapp/image-actions stopped working a few days ago. Looking into the action triggered by the PR, it seems the problem is inside the Compress images section:

```
->> Committing files…
	 *  Head SHA: ffba62c88fc21a806db33d5d3c3f1b3772a24e23
	 *  Tree 8ab94b20d9ed5bf3898f63b52732d30e7f95e25f
	 *  Converting images to blobs…
	 *  Creating tree… BriceChivu bricetravels 8ab94b20d9ed5bf3898f63b52732d30e7f95e25f
(node:1) UnhandledPromiseRejectionWarning: HttpError: Server Error
    at /usr/local/src/image-actions/node_modules/@octokit/request/lib/request.js:56:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/8ffc364a-6071-432d-a859-837c97966fbd">

My calibreapp-image-actions.yml is as follow:
```yml
name: Compress Images
on:
  pull_request:
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    # paths:
    #   - '**.jpg'
    #   - '**.jpeg'
    #   - '**.png'
    #   - '**.webp'
jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          # The `GITHUB_TOKEN` is automatically generated by GitHub and scoped only to the repository that is currently running the action. By default, the action can’t update Pull Requests initiated from forked repositories.
          # See https://docs.github.com/en/actions/reference/authentication-in-a-workflow and https://help.github.com/en/articles/virtual-environments-for-github-actions#token-permissions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '50'
          jpegProgressive: true
          pngQuality: '50'
          webpQuality: '50'
```

Any idea where this bug might come from?

### Code of Conduct

- [x] I agree to follow this project’s Code of Conduct
