### ISSUE TITLE
[Bug] Unable to run on ARM64 based Unbuntu 22.04 self-hosted agent

### ISSUE THREAD

**Issue by 22367rh** [calibreapp/image-actions#293]
### Describe the bug

When trying to run the example workflow_trigger on a self hosted ARM64 Ununtu 22.04 agent I get an error that the docker image wants to run on x64 but obviously as it is an ARM64 SBC this doesn't work. (Error in the relevant section)

### How To Reproduce

1. Setup workflow.yml with the following example settings:

```
name: Compress Images Now
on:
  workflow_dispatch:
jobs:
  build:
    name: Run calibreapp/image-actions
    runs-on: [self-hosted, ARM64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: Compressed Images On Demand Result
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
```

2. Trigger workflow on repo

### Screenshots

![image](https://github.com/user-attachments/assets/52192638-c39e-42fc-8516-bc14c0ede9ec)

### Relevant Log Output

```shell
Run calibreapp/image-actions@main
  with:
    githubToken: ***
    compressOnly: true
    jpegQuality: 80
    jpegProgressive: false
    pngQuality: 80
    webpQuality: 80
    ignorePaths: node_modules/**
/usr/bin/docker run --name ghcriocalibreappimageactionsimageactionsmain_5bb34c --label e9f556 --workdir /github/workspace --rm -e "INPUT_GITHUBTOKEN" -e "INPUT_COMPRESSONLY" -e "INPUT_JPEGQUALITY" -e "INPUT_JPEGPROGRESSIVE" -e "INPUT_PNGQUALITY" -e "INPUT_WEBPQUALITY" -e "INPUT_IGNOREPATHS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "
WARNING: The requested image's platform (linux/amd64)) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/src/image-actions/entrypoint.js: exec format error
```

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct
