### ISSUE TITLE
[Bug] changes the color of images

### ISSUE THREAD

**Issue by ethanneff** [calibreapp/image-actions#302]
### Describe the bug

changes the color of images

before|after

![Image](https://github.com/user-attachments/assets/2ad179d1-e14c-4eda-a458-82e21cd465f1)

### How To Reproduce

example image 

![Image](https://github.com/user-attachments/assets/b8888dbf-5ca0-4493-a375-fe9f4cd69158)

example github action

```yml
# Image Actions will run in the following scenarios:
# - on Pull Requests containing images (not including forks)
# - on pushing of images to `master` (for forks)
# - on demand
# - at 11 PM every Sunday in anything gets missed with any of the above scenarios
# For Pull Requests, the images are added to the PR.
# For other scenarios, a new PR will be opened if any images are compressed.
name: Compress images
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  push:
    branches:
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * 0'
jobs:
  compressImages:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: ${{ github.event_name != 'pull_request' }}
      - name: Create Pull Request
        if: |
          github.event_name != 'pull_request' &&
          steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: Auto Compress Images
          branch-suffix: timestamp
          commit-message: Compress Images
          body: ${{ steps.calibre.outputs.markdown }}

```

### Relevant Log Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project’s Code of Conduct
