### ISSUE TITLE
Run action on diff only

### ISSUE THREAD

**Issue by Luxiyalu** [calibreapp/image-actions#36]
Currently image-actions run on all pull-requests actions, among which, the majority triggers are pushes that have nothing to do with images. Is it possible to filter down the commit to see if there are actually images involved before triggering the action?

Thanks for the good work!

**Comment by Luxiyalu** [comment]
Scratch that, looks like this worked:

```
on:
   pull_request:
     paths:
       - '**.jpg'
       - '**.png'
       - '**.ico'
```
