### ISSUE TITLE
When using git-lfs optimized images are incorrectly commited

### ISSUE THREAD

**Issue by mieszko4** [calibreapp/image-actions#50]
I have a repository with images tracked in git-lfs.
My `.gitattributes`:
```
*.jpg filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
```

So my configuration for github's action checkout step is:

```yml
- name: Checkout Repo
        uses: actions/checkout@master
        with:
          lfs: true # NOTE this line
```

Calibreapp optimizes images well but instead of committing optimized images to git-lfs it commits them directly to git repository (by creating binary files instead of pointers)

I suspect the problem is here: https://github.com/calibreapp/image-actions/blob/f1ea93babb1a9fd08a83d171b8aa5e9fadec0c9f/src/github-commit.js#L52-L77

So I cannot use this action with my current setup :(
Do you plan to support git-lfs repositories?
