### ISSUE TITLE
error in "compress images"

### ISSUE THREAD

**Issue by marionschleifer** [calibreapp/image-actions#59]
Hi there 👋 

First of all, thank you for creating this Github action!

I've tried to add the configuration as shown in the README:

```
name: Compress images
on: 
  pull_request:
    paths:
      - '**.jpg'
      - '**.png'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

In the "Compress images" job, it first runs fine and all images get compressed. Then, at the end, I get the following error:

```
Converting images to blobs…
(node:1) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at response.text.then.message (/usr/local/src/image-actions/node_modules/@octokit/request/lib/request.js:56:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea how I could fix this?
