### ISSUE TITLE
Add support for resizing images

### ISSUE THREAD

**Issue by kaycebasques** [calibreapp/image-actions#60]
On web.dev we never need images larger than `1600px`. I frequently have to ask our contributors to resize their images (in order to keep the repository size down). Are you open to adding image resizing to image-actions or should we look for other solutions?

Edit: We never need images within our main content to be more than `1600px`. There are a few exceptions we'd need to specify but I can share more details later.

**Comment by kaycebasques** [comment]
Thanks for looking into this. Sorry for missing #20 (I recall searching for related issues… don't know how I missed that).

Here's our use case for web.dev:

* Our images are stored alongside our Markdown. E.g. the content for https://web.dev/optimize-fid is at `/src/site/content/en/blog/optimize-fid/index.md` and its hero image is at `/src/site/content/en/blog/optimize-fid/hero2.jpg` and one of the main content images that the Markdown references is at `/src/site/content/en/blog/optimize-fid/lighthouse.jpg`.
* For hero images we always need those to be `3200px` wide and `960px` tall. At minimum, `image-actions` should allow us to specify that it should ignore hero images, perhaps with a glob like `/src/site/content/**/hero.jpg` (we don't currently enforce that all hero images should have the filename `hero.jpg` but we can start).
* For main content images we just want to enforce a maximum width of `1600px` but we want the height to remain proportional, e.g. if the original image is `3200px` wide and `1600px` tall it should be resized to `1600px` wide and `800px` tall.
* Ideally `image-actions` would replace the main content images in-place, rather than just warning that the images are too large. Our goal here is to minimize the work that our contributors need to do. Having to manually resize images is one of our contributors' top gripes ("this seems like it should be automated…").

@bazzadp's proposed config would probably work for us. Here's my first impression of an intuitive config:

```
max-width: 
  default: 1600
  input:
    - '/src/site/content/**'
  ignore:
    - '/src/site/content/**/hero.jpg' # or perhaps just 'hero.jpg'
```

I'm assuming it would automatically detect common image filename extensions.

**Comment by bazzadp** [comment]
@kaycebasques alternatively if you also wanted to enforce the `3200px` maximum width for hero images you could have this config like this under my proposal:

```
max-width: 
  default: 1600
  input:
    - '/src/site/content/**'
  custom:
    3200: 
      - '/src/site/content/**/hero.jpg' # or perhaps just 'hero.jpg'
```

That is provide a 3200 setting rather than ignoring it completely. Wouldn't enforce a `960px` tall though and maybe overkill for your needs but throwing it out there.

**Comment by bazzadp** [comment]
What would also be really cool (maybe as a stage too) would be to create alternative sizes/formats for `scrset`:

```
alternatives:
  input:
    - **XL.jpg
  alt1:
    name: LG
    format: jpg
    width: 1600px
  alt2:
    name: MD
    format: jpg
    width: 800px
  alt3:
    name: SM
    format: jpg
    width: 400px
  alt4:
    name: LG
    format: png
    width: 1600px
  alt5:
    name: MD
    format: png
    width: 800px
  alt6:
    name: SM
    format: png
    width: 400px
```

So if you fed it a '/src/site/content/article1/hero-XL.jpg` it would automatically create the following images:
- `/src/site/content/article1/hero-LG.jpg`
- `/src/site/content/article1/hero-MD.jpg`
- `/src/site/content/article1/hero-SM.jpg`
- `/src/site/content/article1/hero-LG.png`
- `/src/site/content/article1/hero-MD.png`
- `/src/site/content/article1/hero-SM.png`
