### ISSUE TITLE
Compressed files are marked for compression

### ISSUE THREAD

**Issue by TomasBarry** [calibreapp/image-actions#63]
```yml
name: Compress images

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Compress Images
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.github_token }}
          jpegQuality: "80"
          pngQuality: "80"
          webpQuality: "80"
          ignorePaths: "node_modules/**,build"

```

The above is our GitHub Action.

When we create a pull request, a number of files compressed by the action. However, if we make any changes to the pull request with the compressed assets a subset of the compressed assets are re-compressed.

I would have assumed that the compressed file could not be compressed again (through the same algorithm) but that is what appears to be happening.

**Comment by benschwarz** [comment]
@TomasBarry Here's what image actions does: 

* After each push to a PR, image-actions is invoked
* Images that match the `glob` finder will be processed
* Images that are ['significantly changed'](https://github.com/calibreapp/image-actions/blob/master/src/image-processing.js#L63) are committed and added to the markdown summary

From what you're saying, it sounds like there's a byte difference of more than 1% each time you've committed. 
Is that the case? Do you have any numbers/metrics to share with this report? 

It might be that we need to increase the change threshold (say ~3%) to accommodate for cases like this. 

Any additional information you have to share will be helpful :-)

**Comment by TomasBarry** [comment]
Hi @benschwarz. I actually can't find the data of the most recent examples because the comments were deleted...

An adjustable threshold would be pretty nice. But I was also thinking that it would be good to only run the action on assets in the pull request. In theory, assets not in the pull request should already be compressed and only touched assets should be in a pull request.

If you can point me in the right direction I don't mind having a look at implementing either of the above suggestions.

**Comment by benschwarz** [comment]
Hey @TomasBarry, not sure what version of the image-actions config you're using, but if you haven't updated in a while, I'd recommend doing so. 

The suggested default configuration will only run when image files (jpgs, webps etc) are changed within that pull request. Additionally there's also an configuration example for image actions to create pull requests, rather than jump in on work in progress. That might suit your use case better. 

Could you check those out and report back?

**Comment by bazzadp** [comment]
Do we not need you to do a release for us to be able to use that?

Also while it’s true that using the config in the README will only run if the PR contains images, of will then compress ALL images - not just those images in the PR. Personally I think that’s handy, but I can see why a `changedFilesOnly` flag could be useful - especially for larger repos.

**Comment by benschwarz** [comment]
> Do we not need you to do a release for us to be able to use that?

@bazzadp Nope. Because GitHub Actions doesn't cache docker image builds. [image-actions references a pre-built from the main branch Dockerhub hosted image.](https://github.com/calibreapp/image-actions/blob/master/action.yml#L46). 

Otherwise folks would have to wait 10+ mins for image actions to run 😓

**Comment by TomasBarry** [comment]
@benschwarz, we are using `calibreapp/image-actions@1.1.0`.

As @bazzadp said, a `changedFilesOnly` flag would be great but I was not aware that we could use it to create a separate PR which we might actually adopt for the time being.

Is there any intention of a `changedFilesOnly` flag in the future? I'd really back this feature given it would make QA on a PR constrained and on larger repos where many teams own many different parts of the code and you're not touching another teams code unless you meant to.

**Comment by benschwarz** [comment]
@TomasBarry, I'm not sure about adding a `changedFilesOnly` config flag. It somewhat goes against the intention of having an action that ensures all images are compressed. Of course, I'd not considered the multi-team-repo-ownership use case. 🤔 

Did you switch over to the "Create separate PR" config? Is that likely to work better? 

💭 Implementation note: If we were to add a `changedFilesOnly` flag, it would conflict with `compressOnly`. It would need to warn about that (and be documented as such).

**Comment by bazzadp** [comment]
> 💭 Implementation note: If we were to add a `changedFilesOnly` flag, it would conflict with `compressOnly`. It would need to warn about that (and be documented as such).

Not sure why it would conflict? Obviously it couldn't be used for the on-demand or scheduled options, but it could still be used with pull_requests and pushes if we checked files changed in those.

Personally I think this could still be helpful for large repos, as imaging the run time for the image action on those could be significant. With a `changesFilesOnly` option pull requests and pushes can be quick, and the scheduled run, where a user is not waiting for the result, can take longer to do the full repo and make sure no other images were missed, so still abiding by the intention of ensuring all images are compressed.

**Comment by benschwarz** [comment]
@bazzadp I should've said "could" conflict, was just trying to be mindful of other stuff that was in flight at the time. 

`changedFilesOnly` seems like a reasonable idea, although I think we've got options that work well enough for the more common use cases. 

Leaving this issue open to gauge interest for a while — if you've stumbled across this and think it'd be a useful feature, please let us know.

**Comment by benschwarz** [comment]
Closing this off for now, feel free to weigh in if you have ideas 💭

**Comment by hasan-wajahat** [comment]
Hey @benschwarz I have this setting for compressing image:

```yml
 - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          ignorePaths: 'node_modules/**,build'
          compressOnly: true
          jpegQuality: '80'
          jpegProgressive: false
          pngQuality: '80'
          webpQuality: '80'

- name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Compressed raster images
          branch: compress-raster-images
          branch-suffix: timestamp
          body: ${{ steps.calibre.outputs.markdown }}
```

Calibre keeps opening PR for already optimized images. But this only happens for WebP images and every time the change is of around 1-1.3%.
