### ISSUE TITLE
Feature: Scheduled/periodic runs

### ISSUE THREAD

**Issue by benschwarz** [calibreapp/image-actions#70]
At the moment `image-actions` runs only when you've updated a pull request. Images are optimised and committed inline. 
In most cases, this works quite well, but there are some drawbacks to this approach: 

* The next time you push to your PR, you'll need to pull first (because image-actions has produced a new commit)
* By adding a commit, some test suites will run (again), clogging up builds for a longer duration
* If you're displeased with the image compression (or some other issue), you're not able to choose if you want the changes or not. This isn't something I've faced personally, but either way the fix (remove the commit and then turn off image actions) isn't very straightforward and feels like busy work. 

By using GitHub Actions scheduler, `image-actions` could:

* Be run periodically (as often as you like - daily, weekly, monthly, etc) 
* If there's optimisations, a pull request could be created -- rather than interrupting WIP (similar to dependabot or other tools)

This issue stands as a mark of intent to implement. If anyone has the bandwidth to help, please let me know or submit a PR 🏆

**Comment by bazzadp** [comment]
When #54 is merged then this can be done with an action something like this:

```yml
name: Compress images every morning at 8am, opening PRs if necessary
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 8 * * *'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: "true"

      - name: Create New Pull Request
        uses: peter-evans/create-pull-request@master
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
```
