### ISSUE TITLE
Documentation on creating a GITHUB_TOKEN secret 

### ISSUE THREAD

**Issue by coliff** [calibreapp/image-actions#8]
I added: 
```
name: Compress images
on: pull_request
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
```
as `.github/workflows/calibreapp-image-actions.yml` to a private repo. The bottom of the README for this project says:

> This action requires a GITHUB_TOKEN secret so that it has access to commit the optimised images to your repository.

Where do you create that GITHUB_TOKEN secret though? Or is it done automatically? I see you can add Secrets via the Settings > Secrets menu, but do I need to enter a specific name? This part isn't very clear....
