### ISSUE TITLE
Compress & commit to master on push

### ISSUE THREAD

**Issue by searls** [calibreapp/image-actions#83]
Was just reading through the documentation which is clearly oriented towards pull-request workflows—could you help advise me on how I might use this action (or modify it) to just compress & commit images on every push to master? 

For folks using a web CMS like Netlify CMS or Forestry to publish a solo blog, it's more typical to just commit every change to master, so this workflow would be pretty fantastic if it could run automatically without needing to introduce pull requests.

Thanks for your time and consideration!

**Comment by bazzadp** [comment]
@searls you can automatically create a pull request on pushes to master as detailed [in the documentation](https://github.com/calibreapp/image-actions#handling-pull-requests-from-forked-repos) which would be the recommended way rather than blindly committing to master without oversight of what had changed.

If you really, really, really wanted to just commit the results of imagine compression directly to master then you could alter that YAML file to something like this but, as this is not recommended, I don't think Calibre would add this to the documentation.

```yml
name: Compress Images on Push to Master with Commit
on:
  push:
    branches:
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Commit changes direct to master
        run: |
          echo "Adding images"
          #change below to whatever path you want to add, or alternatively change further down to "git commit -am"
          git add src/images
          echo "Committing changes"
          git diff-index --quiet HEAD || git commit -m "Optimised images"
          git push
```

**Comment by searls** [comment]
That did it! Fantastic, thanks. For anyone who finds this from google, note that the workflow will want email & user config set. This is where I landed:

```yml
name: Compress Images on Push to Master with Commit
on:
  push:
    branches:
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Commit changes direct to master
        run: |
          echo "Committing compressed images"
          git config --global user.email "YOUR EMAIL"
          git config --global user.name "YOUR  NAME"
          git diff-index --quiet HEAD || git commit -am "Compressing images"
          git push
```
