### ISSUE TITLE
[Bug] Fails on a reopened PR

### ISSUE THREAD

**Issue by nathanaelhoun** [calibreapp/image-actions#84]
## Describe the bug
When a PR is closed and then reopened, the action job fails with ` Error:  Check run has action reopened . Wants: synchronize or opened`

## How To Reproduce

1. Open a PR
2. Wait for a job to finish
3. Close the PR and then reopen it
4. Job fails. See error

## Expected behaviour
The jobs does not fail (either do not run or run and be skipped)

## Additional context
Config:
```yaml
name: Compress images
on: pull_request
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Relevant code seems to be [entrypoint.js#L27](https://github.com/calibreapp/image-actions/blob/master/entrypoint.js#L27)
