### ISSUE TITLE
[Bug] ignorePaths doesn't seem to work

### ISSUE THREAD

**Issue by hypothete** [calibreapp/image-actions#85]
## Describe the bug
I'm working on a repo that already contains an animated webp file. Calibre keeps trying to optimize the animation out of the image when I make PRs. From the documentation it looks like I should be able to add `ignorePaths` with a comma-separated string of globs to the workflow in order to ignore the webp, but I can't get it to work. I'm pretty new to GH Actions so my apologies if there's an obvious solution here, but so far I'm feeling pretty stuck. Here's what I've tried.

## How To Reproduce
1. Use `ignorePaths` to explicitly ignore webp paths:

```
name: Optimize Images
on: pull_request
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          ignorePaths: '**.webp'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

2. Try explicitly setting `INPUT_IGNOREPATHS`:

```
name: Optimize Images
on: pull_request
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          INPUT_IGNOREPATHS: '**.webp'
```

3. Download and build the repo, run `INPUT_IGNOREPATHS="**.webp" npm run test`

## Expected behaviour
In the first 2 cases I can see from logging that ignorePaths remains the default value of `[node_modules/**]`.  On the third test ignorePaths updates successfully, but the test webp still gets compressed. Am I doing something wrong here, or is this a bug?
