### ISSUE TITLE
[Feature Request] Only optimized changed images

### ISSUE THREAD

**Issue by rachmari** [calibreapp/image-actions#92]
Thank you for creating this well-documented action! 🙌 

Also, please forgive me if I missed any documentation or settings that would solve what I'm requesting. 😅 

## What problem would this feature solve?

It looks like this action will optimize all images in the repo that match any selected paths. If that is true, I'd love the ability to be able to only optimize images that are part of the commit that triggered the workflow. This would speed up a potentially long process and target only changed images. 

We have a very large directory of images that takes up to 5 hours to compress, but if we know that the existing images are already compressed, it'd be great to only optimize images that are added or updated.

## Describe the solution you’d like to see

An input parameter that allows you to select targeting only images that are part of the commit that triggered the workflow. This would likely only be applicable to `pull_request` and `push` events. 

If the input parameter is set, the action would retrieve the list of changed files and find any image files. If there are changed image files, those images will be compressed.

**Comment by benschwarz** [comment]
Hey @rachmari ! 👋 

> We have a very large directory of images that takes up to 5 hours to compress 

Whoa! That's … a lot 😅

The current image-actions config (found in `README`) contains: 

```
name: Compress Images
on:
  pull_request:
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
```

This config means that the action will only be run when images files have been updated… but what you're asking is _slightly different_ in that you ONLY want to process the files that have been updated, rather than the whole set. 

Is that correct?
